matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - ./gradlew clean test
        - ./gradlew clean integrationTest
        - ./gradlew clean check

    - language: node_js
      node_js: "8"
      sudo: required
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
        - npm install -g @angular/cli@6.1.4
        - cd frontend
        - npm install
      script:
        - ng lint
        - ng test --watch=false
      after_script:
        - cd ..