matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - cd backend
        - ./gradlew clean test
        - ./gradlew clean check

    - language: node_js
      node_js: "8"
      before_script:
        - npm install -g @angular/cli
      script:
        - ng lint
        - ng test