matrix:
  include:
    - language: java
      jdk: openjdk8
      script:
        - ./gradlew clean spotlessCheck test integrationTest check

    - language: node_js
      node_js: "10"
      sudo: required
      services:
        - xvfb
      before_script:
        - npm install -g @angular/cli@6.1.4
        - cd frontend
        - npm install
      script:
        - ng lint
        - ng test --watch=false --configuration=localhost
      after_script:
        - cd ..
