version: '3'
services:
    web:
        image: com.tngtech.apicenter/backend:1.0.0-snapshot
        ports:
            - 8080:8080
        depends_on:
            - db
    db:
        image: postgres:latest
        volumes:
            - ./backend/create.sql:/docker-entrypoint-initdb.d/create.sql
        environment:
            - POSTGRES_PASSWORD=sample
            - POSTGRES_USER=sample
            - POSTGRES_DB=sample
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5434:5432

