version: '3'
services:
    web:
        image: com.tngtech.apicenter/backend:1.0.0-snapshot
        ports:
            - 8080:8080
        depends_on:
            - db
    db:
        image: postgres:latest
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=sample
            - POSTGRES_USER=sample
            - POSTGRES_DB=sample
        ports:
            - 5434:5432
volumes:
    pgdata:
