name: "Validate Gradle Wrapper"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validation:
    name: "Gradle wrapper validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
